backend:
  name: git-gateway
  branch: master

media_folder: public/assets
public_folder: assets

collections:
  - name: 'pages'
    label: 'Páginas'
    delete: false
    editor:
      preview: false
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }

  - name: 'config'
    label: 'Configurações'
    delete: false
    editor:
      preview: false
    files:
      - name: 'authors'
        label: 'Autores'
        file: 'content/config/authors.yml'
        fields:
          - name: 'authors'
            label: 'Autores'
            label_singular: 'Autor'
            widget: list
            fields:
              - { label: 'Slug', name: 'slug', widget: 'string' }
              - { label: 'Nome', name: 'name', widget: 'string' }
      - name: 'tags'
        label: 'Tags'
        file: 'content/config/tags.yml'
        fields:
          - name: 'tags'
            label: 'Tags'
            label_singular: 'Tag'
            widget: list
            fields:
              - { label: 'Slug', name: 'slug', widget: 'string' }
              - { label: 'Tag', name: 'name', widget: 'string' }

  - name: 'blog'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Resumo', name: 'description', widget: 'string' }
      - {
          label: 'Data de publicação',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          dateFormat: 'DD/MM/YYYY',
          timeFormat: false,
        }
      - { label: 'Imagem destaque', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Autor',
          name: 'author',
          widget: 'relation',
          collection: 'config',
          file: 'authors',
          search_fields: ['authors.*.name'],
          display_fields: ['authors.*.name'],
          value_field: 'authors.*.slug',
        }
      - {
          label: 'Tags',
          label_singular: 'Tag',
          name: 'tags',
          widget: 'list',
          summary: '{{fields.tag}}',
          field:
            {
              label: 'Tag',
              name: 'tag',
              widget: 'relation',
              collection: 'meta',
              file: 'tags',
              search_fields: ['tags.*.name'],
              display_fields: ['tags.*.name'],
              value_field: 'tags.*.slug',
            },
        }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }

      # - name: 'tags'
      #   label: 'Tags'
      #   widget: list
      #   fields:
      #     - name: 'tag'
      #       label: 'Tag'
      #       widget: 'string'
